
package org.ejbca.core.protocol.ws.jaxws;

import java.security.cert.CertPath;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "CertPathValidatorException", namespace = "http://ws.protocol.core.ejbca.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertPathValidatorException", namespace = "http://ws.protocol.core.ejbca.org/", propOrder = {
    "certPath",
    "index",
    "message"
})
public class CertPathValidatorExceptionBean {

    private CertPath certPath;
    private int index;
    private String message;

    /**
     * 
     * @return
     *     returns CertPath
     */
    public CertPath getCertPath() {
        return this.certPath;
    }

    /**
     * 
     * @param certPath
     *     the value for the certPath property
     */
    public void setCertPath(CertPath certPath) {
        this.certPath = certPath;
    }

    /**
     * 
     * @return
     *     returns int
     */
    public int getIndex() {
        return this.index;
    }

    /**
     * 
     * @param index
     *     the value for the index property
     */
    public void setIndex(int index) {
        this.index = index;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
